Added SnakeGame
todorzag/c-sharp-oop pull request #19
Opened 2022-08-29 07:23 UTC by todorzag

2022-08-30 13:07 UTC, todorzag commented on SnakeGame/SnakeGame/Game.cs
> +            Thread.Sleep(2000);
How to move Thread.Sleep() to main?

2022-09-13 07:42 UTC, todorzag commented on SnakeGame/SnakeGame/Game.cs
> +        public delegate void Del();
Need to remove

2022-09-13 15:12 UTC, mvlt requested changes

2022-09-13 15:12 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +            _snakeBody = new List<SnakePart>
What if we want to make starting length of the snake configurable

2022-09-13 15:12 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +            SnakeHead = new SnakePart(1, 4, "○");
Isn't the head part of the body

2022-09-13 15:12 UTC, mvlt commented on SnakeGame/SnakeGame/SnakePart.cs
> +        public SnakePart(int x, int y)
Do we need 2 constructors for different type of displaying. Snake part should be able to print itself differently based on a param

2022-09-13 15:12 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +            SnakeHead.X += x;
Why don't we check here if the move is appropriate?

2022-09-13 15:12 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +        public void UpdateBodyPosition()
Another way which we could try is adding a new element in front and removing the last one.

2022-09-13 15:12 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +            SnakeHead.X += x;
Also do the teleport here

2022-09-13 15:12 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +        private bool ShouldEndGame()
Shouldn't this be part of the Snake class

2022-09-13 15:12 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +            moveMethod(directionNum);
Better use try catch and move the logic for teleport and game over checks in snake class

2022-09-13 15:12 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +        public SnakePart SnakeHead;
In Snake class shouldn't be just named Head (Snake.Head not Snake.SnakeHead)

2022-09-13 15:15 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +        private void PopulateDirections()
Why do we initialize it like this

2022-09-14 10:40 UTC, mvlt requested changes
Think also about interfaces for some of the classes

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +        public bool OnApple((int,int) applePosition)
Do you need this method

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +        public void RenderSnake()
Can we handle the logic for different symbols of the snake in render method

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +        public bool ShouldEndGame()
Need better naming

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +            for (int i = _snakeBody.Count - 1; i > 0; i--)
Is there better way for that job

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +            if (CheckIfOutOfBounds())
Similar logic like shouldTeleport

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +            if (IsKeyInDictionary(keyPressed))
Why wrapped in function

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +                direction = _lastDirection;
Seems a little hacky try other way

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +                if (!_snake.CheckSpawnOnSnake(_applePosition))
Why wrapped

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +            while (!HasEnded);
Here also checking hasEnded, so why not end here but call Over in program.cs

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +        public void EatApple()
Change the name to tell what the function is doing

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +        private string _keyPressed = "RightArrow";
Why do you create enum and dictionary and hardcoded here

2022-09-14 10:40 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +        private Dictionary<string, Directions> movementDirections
Do we need a dictionary? Could we define the enum other way so we don't need this dictionary?

2022-09-14 10:50 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +        public void ClearLastSnakePart()
I was expecting to remove it from snake body

2022-09-14 10:52 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +            int x = Head.X;
Head.X is more explainable than x why assigning to a new variable

2022-09-19 15:21 UTC, mvlt requested changes

2022-09-19 15:21 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +        private Snake _snake = new Snake(4);
Better user to be able to choose starting length ex. from 0 to 10

2022-09-19 15:21 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +        private int _consoleHeight = Console.WindowHeight;
why do we need to store height and width in fields

2022-09-19 15:21 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +        private bool MoveIsNotPossible(bool hasWalls)
Not the best name for this function

2022-09-19 15:21 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +            if (!SnakeIsAlive)
Do we need to check if Snake is Alive here

2022-09-19 15:21 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +        private void GameOver()
Game over not best name if also is saving the score

2022-09-19 15:21 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +        private void AppleHandler()
AppleHandler is also adding snake parts

2022-09-19 15:21 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +            Console.Clear();
Can we clear the console in some of the functions which are called in the Main Process

2022-09-19 15:21 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +        private void StartingProcesses()
Why do we need to spawn apple and render the snake here

2022-09-19 15:21 UTC, mvlt commented on SnakeGame/SnakeGame/Game.cs
> +        private void WaitForKeyPress()
Waiting for key press is also writing starting logo

2022-09-19 15:21 UTC, mvlt commented on SnakeGame/SnakeGame/Snake.cs
> +        private bool CheckTeleport(bool hasWalls)
better name

2022-09-20 14:29 UTC, mvlt requested changes

2022-09-20 14:29 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +        private IDiffilcultyHandler _diffilcultyHandler = new DiffilcultyHandler();
Syntax error. Violation of Dependency Inversion Principle.

2022-09-20 14:29 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +        private string _user;
Violation of Single Responsibility Principle.

2022-09-20 14:29 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +        private void OpenStartingMenu()
SRP

2022-09-20 14:29 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +                throw new ArgumentOutOfRangeException
SRP

2022-09-20 14:29 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +        private void SpawnApple()
SRP

2022-09-20 14:29 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +            return _applePosition == _snake.Head.Position;
Is this responsibility for the game or the snake

2022-09-28 10:12 UTC, mvlt requested changes

2022-09-28 10:12 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Snake.cs
> +        private bool MoveIsIllegal(bool hasWalls)
This name sounds more like a statement than a function

2022-09-28 10:12 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Snake.cs
> +        public void MoveX(int x, bool gameHasWalls)
x ?

2022-09-28 10:12 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +        private IScoreManager _scoreManager =
We could pass scoreManager as a parameter to the Game class and initialize it in the constructor

2022-09-28 10:12 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +        private IDiffilcultyHandler _diffilcultyHandler =
DifficultyHandler also

2022-09-28 10:12 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +            _snake = Factory.CreateSnake(_config.SnakeLength);
Snake could also be passed to the constructor

2022-09-28 10:12 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Snake.cs
> +        public (int, int) CurrentPosition
Are we using this only in the tests

2022-09-28 10:12 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/SnakeMoveChecker.cs
> +            if (CheckIfOutOfBounds(newPosition) && !gameHasWalls)
If game has no walls no need to evaluate CheckIfOutOfBounds

2022-09-28 10:12 UTC, mvlt commented on SnakeGame/SnakeGame/Utils/ScoreManager.cs
> +        public void RenderLogo()
We could have something like fancyMessageRenderer which takes the score and do the rendering of all logos. I think score manager should not be responsible for that also

2022-09-28 10:12 UTC, mvlt commented on SnakeGame/SnakeGame/Utils/StandardMessages.cs
> +    public class StandardMessages
We are not only storing the message content but we also writing them better name for the class

2022-10-12 13:47 UTC, mvlt reviewed
Do we need all implemented interfaces

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Food.cs
> +    public class Food : Point, IFood
Renderable?

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +            ScreenRenderer.StartingScreen();
StartingScreen no verb in the name of the function

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +            ScreenRenderer.GameOverScreen(_scoreManager);
No verb in GameOverScreen and why need the dependence to scoreManager

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +                => TimerCallback(Factory.CreateSwitch), null, 10000, 10000));
Magic numbers

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Utils/ScoreManager.cs
> +        public void CheckScoreUnderZero(ISnake snake)
Do we need scoreManager to be dependent of the snake?

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Utils/ScreenRenderer.cs
> +            Console.WriteLine(Logos.GameOverLogo);
Why not using the writer?

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Utils/Validator.cs
> +    public class Validator
This seems more like snakeLengthValidator

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +                    _scoreManager.Set(_snake.Body, _diffilcultyHandler);
Why scoreManager also need to know about defficultyHandler

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Snake.cs
> +        public void RemovePart()
Remove tail better. With name RemovePrat I have the feeling that with this function I can remove every part but I can't

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Snake.cs
> +            ClearLastBodyPart();
RemovePart is calling ClearLastBodyPart with this naming I am assuming they are doing same thing

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Snake.cs
> +                    MoveY(1);
Magic number

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Snake.cs
> +            if (isValid == true)
Boolean expression with three cases?

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Utils/SnakeMoveChecker.cs
> +            ISnake snake, IPoint newPosition)
Do we need the whole snake object

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Utils/Writer.cs
> +                {
This logic seems strange. Is there more simple approach?

2022-10-12 13:47 UTC, mvlt commented on SnakeGame/SnakeGame/Interfaces/IOnConsume.cs
> +    public interface IOnConsume
Consumable?

2022-10-18 08:24 UTC, mvlt requested changes

2022-10-18 08:24 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +            ScreenRenderer.StartingScreen();
Again no verb in the name of the function

2022-10-18 08:24 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Game.cs
> +            ScreenRenderer.GameOverScreen(_scoreManager);
And here why marked as resolved

2022-10-18 08:24 UTC, mvlt commented on SnakeGame/SnakeGame/Classes/Strategies/AddSnakePartStrategy.cs
> +    public class AddSnakePartStrategy : IConsumable
How many times this strategy will be instantiated?

2022-10-18 08:24 UTC, mvlt commented on SnakeGame/SnakeGame/Constants/Logos.cs
> +        public static string GenerateScoreLogo(int scoreInt)
Should this functionality be part of Logos class

2022-10-18 08:29 UTC, todorzag commented on SnakeGame/SnakeGame/Classes/Game.cs
> +            ScreenRenderer.GameOverScreen(_scoreManager);
Sorry my bad, will fix

2022-11-03 15:00 UTC, merged